### ISSUE TITLE
A PLACEMENT_TOP_ABOVE_FRAME embossed titlebar of height 1 is an error

### ISSUE THREAD

**Issue by io7m** [io7m-com/jsycamore#2]
It triggers an assertion failure:

```
Exception in thread "AWT-EventQueue-0" org.valid4j.errors.RequireViolation: Rendered rectangle height must be positive
    at org.valid4j.impl.RequireViolationPolicy.handleViolation(RequireViolationPolicy.java:19)
    at org.valid4j.impl.CheckingPolicy.check(CheckingPolicy.java:25)
    at org.valid4j.Assertive.require(Assertive.java:150)
    at com.io7m.jsycamore.core.renderer.SyEmbossed.rectangle(SyEmbossed.java:83)
```

**Comment by io7m** [comment]
This is now invalid: `PLACEMENT_TOP_ABOVE_FRAME` is gone.
